import React, { PureComponent } from "react";
import Head from "next/head";
import Image from "next/image";
import { Box } from "@chakra-ui/react";
import { Container } from "@chakra-ui/react";
import DefaultLayout from "../components/layouts/DefaultLayout";

class Home extends PureComponent {
    constructor(props) {
        super(props);

        this.state = {
            counter: 1
        };
    }
    render() {
        return (
            <DefaultLayout>
                <div className="page-content home-wrapper">
                    <Head>
                        <title>Tiktok - NextJS</title>
                        <meta name="description" content="Generated by create next app" />
                        <link rel="icon" href="/favicon.ico" />
                    </Head>
                </div>
            </DefaultLayout>
        );
    }
}

export default Home;
