import Head from "next/head";
import Image from "next/image";
import { Box } from "@chakra-ui/react";

export default function Home() {
    return (
        <div className="container">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="container">
                <Box w="100%" h="200px" bgGradient="linear(to-r, green.200, pink.500)" />
            </div>
        </div>
    );
}
